# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31756989e00968a49acc74bb6abca6dd7e21cb410a4ac34b188b029484d686d473d100059f10d3047e407385e5c70941bdc5b7f62bd1847a2fb393b60b3e5967

test:
  secret_key_base: cc82dfcadf09339274ed4272b2aa1b5ed45a8432167e86bd8931d7e2716306f6a835e3ceb8a72936f229110a35af3be223b6802003277bf6fd0ec638d8b2f6db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
